### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by amouro**
Add Korean translation based on moment.js locale for #135 
 https://github.com/moment/moment/blob/develop/locale/ko.js

### CODE REVIEW

**Comment by ansata2001** [comment]
@fightbulc could you please accept the PR

**Comment by dmarkowicz** [comment]
Locale file name should be `ko_KR.php`.

**Comment by amouro** [comment]
It is ko_KO.php in commit.
I was miss typing in commit msg.

**Comment by dmarkowicz** [comment]
In commit is ko_KO.php. Correct locales for Korean according to [ICU standard](https://www.localeplanet.com/icu/) are:
- ko | Korean
- ko_KP | Korean (North Korea)
- ko_KR | Korean (South Korea)

There is no KO country code. So translation file name should be either `ko_KR.php` or `ko.php` (if KP and KO dialects are same). But moment.php lib prefers full locales with country code that's why I suggested `ko_KR.php`.

**Comment by fightbulc** [comment]
@dmarkowicz will go with you filename suggestion. thanks

**Pull request merged**
