### PR TITLE
initial Czech locales

### PR DESCRIPTION
**Pull request by ptica**
hi, I tried to handle the different grammatical cases Czech language needs for relative future and past times by assigning a function ['relativeTime'][various_keys] but the args I got are not much helpful - so I opted for word forms that should be suitable for the past variant (which seems more used to me)

### CODE REVIEW

**Comment by fightbulc** [comment]
Hey @ptica, thanks for supporting the lib. What args would you need to handle this?

**Comment by ptica** [comment]
the computed numbers that will get replaced, if I've tried it ok, I will just get the moment vo, don't I?

**Comment by fightbulc** [comment]
Just pushed a new version. You can now use ```function(Moment $m) { return ''; }``` for the values of ```calendar``` and ```relativeTime```.

Example for calendar ```sameDay```:

```php
return array(
    "months"        => explode('_', 'January_February_March_April_May_June_July_August_September_October_November_December'),
    "monthsShort"   => explode('_', 'Jan_Feb_Mar_Apr_May_Jun_Jul_Aug_Sep_Oct_Nov_Dec'),
    "weekdays"      => explode('_', 'Monday_Tuesday_Wednesday_Thursday_Friday_Saturday_Sunday'),
    "weekdaysShort" => explode('_', 'Mon_Tue_Wed_Thu_Fri_Sat_Sun'),
    "calendar"      => array(
        "sameDay"  => function(Moment $m) { \* do something *\ return ''; },
        "nextDay"  => '[Tomorrow]',
        "lastDay"  => '[Yesterday]',
        "lastWeek" => '[Last] l',
        "sameElse" => 'l',
        "withTime" => '[at] H:i',
        "default"  => 'd/m/Y',
    ),
    "relativeTime"  => array(
        "future" => 'in %s',
        "past"   => '%s ago',
        "s"      => 'a few seconds',
        "m"      => 'a minute',
        "mm"     => '%d minutes',
        "h"      => 'an hour',
        "hh"     => '%d hours',
        "d"      => 'a day',
        "dd"     => '%d days',
        "M"      => 'a month',
        "MM"     => '%d months',
        "y"      => 'a year',
        "yy"     => '%d years',
    ),
    "ordinal"       => function ($number)
    {
        $n = $number % 100;
        $ends = array('th', 'st', 'nd', 'rd', 'th', 'th', 'th', 'th', 'th', 'th');

        if ($n >= 11 && $n <= 13)
        {
            return $number . '[th]';
        }

        return $number . '[' . $ends[$number % 10] . ']';
    },
    "week"          => array(
        "dow" => 1, // Monday is the first day of the week.
        "doy" => 4  // The week that contains Jan 4th is the first week of the year.
    ),
);
```

**Comment by ptica** [comment]
I would probably need a bit more pushing in the right direction:
so in the 'y' callable

```
  "relativeTime"  => array(
        "future" => 'za %s',
        "past"   => 'před %s',
        "yy"      => function () {
                        var_export(func_get_args());
                        if ($direction == 'future' and $count > 4) return '%s let';
                        if ($direction == 'future' and $count <= 4) return '%s roky';
                        if ($direction == 'past' and $count > 4) return '%s lety';
                        ....
                    },
```
how do get to $direction and to the number of years ($count) that will get replaced?

**Comment by fightbulc** [comment]
Hey @ptica, just pushed another update.

The closure for the ```relativeTime``` locale receives now the following params:

```php
function($count, $direction, Moment $m) {}
```

That should do the trick now, right?

**Comment by ptica** [comment]
Sure!
cs_CZ is alright by now I think :)
thanks!

**Comment by fightbulc** [comment]
@ptica, I abstracted the logic of your conditions into 2 functions. Could you have another look before I release the new version?

https://github.com/fightbulc/moment.php/blob/master/src/Locales/cs_CZ.php

Thanks!

**Comment by ptica** [comment]
looking at 059888 and the result of https://github.com/fightbulc/moment.php/blob/master/tests/cs_CZ.php seems well to me
-- I am not that proficient with phpunit  - how do I write a proper test for the locale?

**Comment by fightbulc** [comment]
I think this guy had a nice intro for phpunit: https://jtreminio.com/2013/03/unit-testing-tutorial-introduction-to-phpunit/

I guess I will release it for now. We can patch later in case something is off.

Thanks @ptica for putting the time in.

**Comment by fightbulc** [comment]
I think this guy had a nice intro for phpunit: https://jtreminio.com/2013/03/unit-testing-tutorial-introduction-to-phpunit/

I guess I will release it for now. We can patch later in case something is off.

Thanks @ptica for putting the time in.

**Comment by ptica** [comment]
thank you for the lib!
README could mention the cs_CZ now :)

**Comment by fightbulc** [comment]
Just updated README and released.

**Pull request merged**
